In [1]:
import numpy as np

# 3-1 Basics of numpy

In [3]:
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

Dynamic typing is not supported in numpy. 즉, 하나의 data type만으로 array를 구성할 수 있다.

In [5]:
print(test_array[3])
print(type(test_array[3]))

8.0
<class 'numpy.float64'>


In [17]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
matrix_1 = np.array(test_matrix)
matrix_1

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [13]:
print(np.array(test_matrix).reshape(8,))
print(np.array(test_matrix).reshape(8,).shape)

[1 2 3 4 1 2 5 8]
(8,)


In [24]:
matrix_1.reshape(-1,2).shape

(4, 2)

In [33]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

# 3-2 Array indexing and slicing

In [36]:
test_example = np.array([[1,2,3], [4.5, 5, 6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
test_example[0,0] = 12
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [41]:
test_example[0][0] = 5
test_example

array([[5, 2, 3],
       [4, 5, 6]])

In [46]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [51]:
a[1,1:3]

array([7, 8])

# 3-3 Array Creation Function

In [53]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [56]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### ones, zeros, empty

In [173]:
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [62]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [63]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### identity, eye

In [68]:
np.identity(n=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [69]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [73]:
np.eye(3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [74]:
np.eye(N=3, M=5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

In [78]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [79]:
np.diag(matrix, k=1)

array([1, 5])

In [80]:
np.random.uniform(0,5,10).reshape(2,5)

array([[0.16531012, 2.71200021, 0.3422616 , 2.35480519, 1.83132896],
       [3.08134167, 2.13809937, 4.60722924, 1.00760212, 1.42967702]])

In [81]:
np.random.normal(0,2,10).reshape(2,5)

array([[ 1.5241085 , -2.41400993, -0.21826233,  1.5938749 ,  3.25665921],
       [ 0.78333286,  3.33275498,  3.68496206, -1.89199667,  0.28485888]])

# 3-4 Numpy Operation Functions

sum, mean, std, concatenate

In [82]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
test_array.sum(dtype=np.float)

55.0

In [87]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
test_array.sum()

78

In [90]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [91]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
test_array.mean()

6.5

In [93]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [94]:
test_array.std()

3.452052529534663

In [95]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [96]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [98]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [101]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [108]:
np.array([5,6]).T

array([5, 6])

In [105]:
np.array([[5,6]]).T

array([[5],
       [6]])

# 3-5 Array Operations

In [109]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
#matrix a + matrix a 연산
b = a + a
b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [113]:
#matrix a - matrix a 연산
b - a

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
#Element-wise operation. matrix의 shape이 같을때 하는 연산
a * a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [118]:
#dot product
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [119]:
#transpose
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
#transpose
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

### Broadcasting

shape이 다른 배열 간 연산을 지원하는 기능

In [122]:
a = np.array([[1,2,3], [4,5,6]])
scalar = 3

In [123]:
#matrix scalar 덧샘
a + scalar

array([[4, 5, 6],
       [7, 8, 9]])

In [124]:
a - scalar

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [125]:
a * scalar

array([[ 3,  6,  9],
       [12, 15, 18]])

In [126]:
a / scalar

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [127]:
a // scalar

array([[0, 0, 1],
       [1, 1, 2]])

In [129]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
print(test_matrix)
print(test_vector)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 20 30]


In [130]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

# 3-6 Comparisons

In [132]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.any(a>5)

True

In [134]:
np.any(a<0)

False

In [135]:
np.all(a>5)

False

In [136]:
np.all(a<10)

True

In [137]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [138]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [139]:
test_a = np.array([1,3,0])
test_b = np.array([5,2,1])
test_a > test_b

array([False,  True, False])

In [140]:
test_a == test_b

array([False, False, False])

In [141]:
(test_a > test_b).any()

True

In [142]:
a = np.array([1,3,0])
np.logical_and(a>0, a<3)

array([ True, False, False])

In [143]:
a

array([1, 3, 0])

In [144]:
np.where(a>0, 3, 2) #where(condition, TRUE, FALSE)

array([3, 3, 2])

In [146]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
#index returned
np.where(a>5)

(array([6, 7, 8, 9]),)

### argmax and argmin

In [148]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [149]:
#index returned
np.argmax(a)

5

In [150]:
#index returned
np.argmin(a)

0

In [151]:
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [152]:
np.argmax(a, axis=1)

array([3, 1, 1])

In [153]:
np.argmin(a, axis=0)

array([0, 0, 2, 2])

# 3-7 Boolean

In [154]:
a = np.array([1,4,0,2,3,8,9,7], float)
a

array([1., 4., 0., 2., 3., 8., 9., 7.])

In [156]:
condition = a>3
condition

array([False,  True, False, False, False,  True,  True,  True])

In [157]:
a[condition]

array([4., 8., 9., 7.])

In [159]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a

array([[ 1.,  4.],
       [ 9., 16.]])

In [160]:
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [170]:
n = 4
test_matrix = np.arange(n**2).reshape(n,n)
test_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [180]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type==0:
        X = np.zeros(shape, dtype)
    elif type==1:
        X = np.ones(shape, dtype)
    elif type==99:
        X = np.empty(shape, dtype)
    return X

In [184]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [200]:
def n_size_ndarray_creation(n, dtype=np.int):
    X = np.arange(n**2, dtype=dtype).reshape(n,n)
    return X

In [201]:
n_size_ndarray_creation(4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [233]:
def change_shape_of_ndarray(X, n_row):
    if n_row == 1:
        X = X.flatten()
    else:
        num_data = X.size
        X = X.reshape(n_row, int(num_data/n_row))
    return X

In [234]:
X = np.ones((32,32), dtype=np.int)
X

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [235]:
change_shape_of_ndarray(X, 1)

array([1, 1, 1, ..., 1, 1, 1])

In [232]:
X.flatten()

array([1, 1, 1, ..., 1, 1, 1])

In [240]:
def concat_ndarray(X_1, X_2, axis):
    if X_1.ndim == 1:
        num_data = X_1.size
        X_1.reshape((1,num_data))
    return np.concatenate((X_1, X_2), axis=axis)

In [265]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [241]:
concat_ndarray(a,b,0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [272]:
a = np.array([[1, 2]])
b = np.array([5, 6, 7])
np.concatenate((a,b), axis=1)

ValueError: all the input arrays must have same number of dimensions

In [270]:
b = np.array([5, 6])
b.size

2