In [22]:
import pandas as pd
import numpy as np

## Import dataset using Pandas

In [2]:
data_url = "https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data"
df_data = pd.read_csv(data_url, sep='\s+', header = None)

In [3]:
df_data.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [4]:
df_data.columns = ['CRIM','ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 
                   'RAD', 'TAX', 'PTRATIO' ,'B', 'LSTAT', 'MEDV']
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

## Vector exercise using numpy

In [23]:
weight_vector = np.array([[1], [1], [1]])
x_vector = np.array([[3], [4], [5]])
weight_vector

array([[1],
       [1],
       [1]])

In [9]:
weight_vector.T.dot(x_vector)

array([[12]])

In [10]:
df_data['weight_0'] = 1
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  weight_0  
0     15.3  396.90   4.98  24.0         1  
1     17.8  396.90   9.14  21.6         1  
2     17.8  392.83   4.03  34.7         1  
3     18.7  394.63   2.94  33.4         1  
4     18.7  396.90   5.33  36.2         1

In [18]:
df_data = df_data.drop('MEDV', axis=1)
df_data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  weight_0  
0     15.3  396.90   4.98         1  
1     17.8  396.90   9.14         1  
2     17.8  392.83   4.03         1  
3     18.7  394.63   2.94         1  
4     18.7  396.90   5.33         1

In [19]:
df_matrix = df_data.as_matrix()
weight_vector = np.random.random_sample((14,1))

/Users/jonghobaeck/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [20]:
df_matrix.shape

(506, 14)

In [21]:
df_matrix.dot(weight_vector)

array([[390.06584391],
       [374.66027984],
       [362.28496229],
       [352.02247367],
       [358.42042033],
       [357.8609889 ],
       [397.66492534],
       [414.72982037],
       [416.86031987],
       [403.26535807],
       [412.56143496],
       [405.67197815],
       [385.89008718],
       [388.96124992],
       [388.55328016],
       [386.08554064],
       [369.30558889],
       [394.60939596],
       [313.7032254 ],
       [389.80208603],
       [398.85555452],
       [400.48888763],
       [407.92734115],
       [410.05636345],
       [405.21498132],
       [345.35113432],
       [391.84982562],
       [349.30414898],
       [399.40265674],
       [391.53744976],
       [388.31515992],
       [394.91705734],
       [307.8389545 ],
       [384.74889094],
       [318.65286209],
       [382.00201565],
       [368.46095913],
       [371.28478541],
       [365.7892222 ],
       [404.02020025],
       [400.39615835],
       [333.83148595],
       [334.27998784],
       [342