In [1]:
import numpy as np

# 3-1 Basics of numpy

In [3]:
test_array = np.array([1,4,5,8], float)
test_array

array([1., 4., 5., 8.])

Dynamic typing is not supported in numpy. 즉, 하나의 data type만으로 array를 구성할 수 있다.

In [5]:
print(test_array[3])
print(type(test_array[3]))

8.0
<class 'numpy.float64'>


In [17]:
test_matrix = [[1,2,3,4], [1,2,5,8]]
matrix_1 = np.array(test_matrix)
matrix_1

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [13]:
print(np.array(test_matrix).reshape(8,))
print(np.array(test_matrix).reshape(8,).shape)

[1 2 3 4 1 2 5 8]
(8,)


In [24]:
matrix_1.reshape(-1,2).shape

(4, 2)

In [33]:
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

# 3-2 Array indexing and slicing

In [36]:
test_example = np.array([[1,2,3], [4.5, 5, 6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
test_example[0,0] = 12
test_example

array([[12,  2,  3],
       [ 4,  5,  6]])

In [41]:
test_example[0][0] = 5
test_example

array([[5, 2, 3],
       [4, 5, 6]])

In [46]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]], int)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [50]:
a[:,2:]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [51]:
a[1,1:3]

array([7, 8])

# 3-3 Array Creation Function

In [53]:
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [54]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [56]:
np.arange(30).reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### ones, zeros, empty

In [173]:
np.zeros(shape=(2,2))

array([[0., 0.],
       [0., 0.]])

In [62]:
np.empty(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [63]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [66]:
test_matrix = np.arange(30).reshape(5,6)
np.ones_like(test_matrix)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

### identity, eye

In [68]:
np.identity(n=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]], dtype=int8)

In [69]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [71]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [73]:
np.eye(3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [74]:
np.eye(N=3, M=5, k=1, dtype=np.int8)

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0]], dtype=int8)

In [78]:
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [79]:
np.diag(matrix, k=1)

array([1, 5])

In [80]:
np.random.uniform(0,5,10).reshape(2,5)

array([[0.16531012, 2.71200021, 0.3422616 , 2.35480519, 1.83132896],
       [3.08134167, 2.13809937, 4.60722924, 1.00760212, 1.42967702]])

In [81]:
np.random.normal(0,2,10).reshape(2,5)

array([[ 1.5241085 , -2.41400993, -0.21826233,  1.5938749 ,  3.25665921],
       [ 0.78333286,  3.33275498,  3.68496206, -1.89199667,  0.28485888]])

# 3-4 Numpy Operation Functions

sum, mean, std, concatenate

In [82]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
test_array.sum(dtype=np.float)

55.0

In [87]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [88]:
test_array.sum()

78

In [90]:
test_array.sum(axis=1), test_array.sum(axis=0)

(array([10, 26, 42]), array([15, 18, 21, 24]))

In [91]:
test_array = np.arange(1,13).reshape(3,4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [92]:
test_array.mean()

6.5

In [93]:
test_array.mean(axis=0)

array([5., 6., 7., 8.])

In [94]:
test_array.std()

3.452052529534663

In [95]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [96]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

In [97]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [98]:
a = np.array([[1,2,3]])
b = np.array([[2,3,4]])
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [101]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6]])
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [108]:
np.array([5,6]).T

array([5, 6])

In [105]:
np.array([[5,6]]).T

array([[5],
       [6]])

# 3-5 Array Operations

In [109]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
#matrix a + matrix a 연산
b = a + a
b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [113]:
#matrix a - matrix a 연산
b - a

array([[1, 2, 3],
       [4, 5, 6]])

In [115]:
#Element-wise operation. matrix의 shape이 같을때 하는 연산
a * a

array([[ 1,  4,  9],
       [16, 25, 36]])

In [118]:
#dot product
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

In [119]:
#transpose
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [120]:
#transpose
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

### Broadcasting

shape이 다른 배열 간 연산을 지원하는 기능

In [122]:
a = np.array([[1,2,3], [4,5,6]])
scalar = 3

In [123]:
#matrix scalar 덧샘
a + scalar

array([[4, 5, 6],
       [7, 8, 9]])

In [124]:
a - scalar

array([[-2, -1,  0],
       [ 1,  2,  3]])

In [125]:
a * scalar

array([[ 3,  6,  9],
       [12, 15, 18]])

In [126]:
a / scalar

array([[0.33333333, 0.66666667, 1.        ],
       [1.33333333, 1.66666667, 2.        ]])

In [127]:
a // scalar

array([[0, 0, 1],
       [1, 1, 2]])

In [129]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
print(test_matrix)
print(test_vector)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 20 30]


In [130]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

# 3-6 Comparisons

In [132]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [133]:
np.any(a>5)

True

In [134]:
np.any(a<0)

False

In [135]:
np.all(a>5)

False

In [136]:
np.all(a<10)

True

In [137]:
a<0

array([False, False, False, False, False, False, False, False, False,
       False])

In [138]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [139]:
test_a = np.array([1,3,0])
test_b = np.array([5,2,1])
test_a > test_b

array([False,  True, False])

In [140]:
test_a == test_b

array([False, False, False])

In [141]:
(test_a > test_b).any()

True

In [142]:
a = np.array([1,3,0])
np.logical_and(a>0, a<3)

array([ True, False, False])

In [143]:
a

array([1, 3, 0])

In [144]:
np.where(a>0, 3, 2) #where(condition, TRUE, FALSE)

array([3, 3, 2])

In [146]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
#index returned
np.where(a>5)

(array([6, 7, 8, 9]),)

### argmax and argmin

In [148]:
a = np.array([1,2,4,5,8,78,23,3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [149]:
#index returned
np.argmax(a)

5

In [150]:
#index returned
np.argmin(a)

0

In [151]:
a = np.array([[1,2,4,7], [9,88,6,45], [9,76,3,4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [152]:
np.argmax(a, axis=1)

array([3, 1, 1])

In [153]:
np.argmin(a, axis=0)

array([0, 0, 2, 2])

# 3-7 Boolean

In [154]:
a = np.array([1,4,0,2,3,8,9,7], float)
a

array([1., 4., 0., 2., 3., 8., 9., 7.])

In [156]:
condition = a>3
condition

array([False,  True, False, False, False,  True,  True,  True])

In [157]:
a[condition]

array([4., 8., 9., 7.])

In [159]:
a = np.array([[1,4], [9,16]], float)
b = np.array([0,0,1,1,0], int)
c = np.array([0,1,1,1,1], int)
a

array([[ 1.,  4.],
       [ 9., 16.]])

In [160]:
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

In [170]:
n = 4
test_matrix = np.arange(n**2).reshape(n,n)
test_matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [180]:
def zero_or_one_or_empty_ndarray(shape, type=0, dtype=np.int):
    if type==0:
        X = np.zeros(shape, dtype)
    elif type==1:
        X = np.ones(shape, dtype)
    elif type==99:
        X = np.empty(shape, dtype)
    return X

In [184]:
zero_or_one_or_empty_ndarray(shape=(3,3), type=99)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [200]:
def n_size_ndarray_creation(n, dtype=np.int):
    X = np.arange(n**2, dtype=dtype).reshape(n,n)
    return X

In [201]:
n_size_ndarray_creation(4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [233]:
def change_shape_of_ndarray(X, n_row):
    if n_row == 1:
        X = X.flatten()
    else:
        num_data = X.size
        X = X.reshape(n_row, int(num_data/n_row))
    return X

In [234]:
X = np.ones((32,32), dtype=np.int)
X

array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]])

In [235]:
change_shape_of_ndarray(X, 1)

array([1, 1, 1, ..., 1, 1, 1])

In [232]:
X.flatten()

array([1, 1, 1, ..., 1, 1, 1])

In [240]:
def concat_ndarray(X_1, X_2, axis):
    if X_1.ndim == 1:
        num_data = X_1.size
        X_1.reshape((1,num_data))
    return np.concatenate((X_1, X_2), axis=axis)

In [265]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
np.concatenate((a,b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [241]:
concat_ndarray(a,b,0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [272]:
a = np.array([[1, 2]])
b = np.array([5, 6, 7])
np.concatenate((a,b), axis=1)

ValueError: all the input arrays must have same number of dimensions

In [270]:
b = np.array([5, 6])
b.size

2

In [2]:
def change_shape_of_ndarray(X, n_row):
    if n_row == 1:
        X = X.flatten()
    else:
        num_data = X.size
        X = X.reshape(n_row, int(num_data/n_row))
    return X

In [15]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [26]:
def concat_ndarray(X_1, X_2, axis):
    if X_1.ndim == 1:
        X_1 = X_1.reshape(1, X_1.size)
    if X_2.ndim == 1:
        X_2 = X_2.reshape(1, X_2.size)
    try:
        return np.concatenate((X_1, X_2), axis=axis)
    except:
        return False

In [29]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])
concat_ndarray(a,b,1)

False

In [50]:
x = np.arange(12, dtype=np.float32).reshape(6,2)
x

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [56]:
x.mean() / x.std()

1.593255

In [58]:
x.mean(axis=0)

array([5., 6.], dtype=float32)

In [61]:
x.std(axis=0)

array([3.4156504, 3.4156504], dtype=float32)

In [63]:
(x - x.mean(axis=0)) / x.std(axis=0)

array([[-1.46385, -1.46385],
       [-0.87831, -0.87831],
       [-0.29277, -0.29277],
       [ 0.29277,  0.29277],
       [ 0.87831,  0.87831],
       [ 1.46385,  1.46385]], dtype=float32)

In [126]:
def normalize_ndarray(X, axis=99, dtype=np.float32):
    if axis == 0:
        return (X - X.mean(axis=0)) / X.std(axis=0)
    elif axis == 1:
        return (X - (X.mean(axis=1).reshape(X.mean(axis=1).size, 1))) / (X.std(axis=1).reshape(X.std(axis=1).size,1))
    else:
        return (X - X.mean()) / X.std()

In [135]:
x = np.arange(12, dtype=np.float32).reshape(6,2)
x.mean(axis=0)

array([5., 6.], dtype=float32)

In [136]:
x

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.]], dtype=float32)

In [137]:
x - x.mean(axis=0)

array([[-5., -5.],
       [-3., -3.],
       [-1., -1.],
       [ 1.,  1.],
       [ 3.,  3.],
       [ 5.,  5.]], dtype=float32)

In [152]:
def save_ndarray(X, filename="test.npy"):
    np.save(filename, arr=X)

In [153]:
X = np.arange(32, dtype=np.float32).reshape(4, -1)

In [154]:
save_ndarray(X, filename)

In [173]:
x = np.arange(32, dtype=np.float32).reshape(4, -1)
x

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.],
       [16., 17., 18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29., 30., 31.]], dtype=float32)

In [239]:
def find_nearest_value(X, target_value):
    pass

In [249]:
X = np.random.uniform(0, 1, 100)
X

array([0.08320944, 0.28163513, 0.43226985, 0.34361974, 0.90638178,
       0.73941163, 0.7671644 , 0.71096114, 0.23839485, 0.32130682,
       0.18391071, 0.31153932, 0.11095775, 0.40159824, 0.76316895,
       0.00879744, 0.44938085, 0.95288302, 0.69350348, 0.86902249,
       0.76969605, 0.21167955, 0.66846311, 0.02230715, 0.46180493,
       0.37258669, 0.91267169, 0.46483   , 0.20740036, 0.54666096,
       0.31027549, 0.83816603, 0.13612515, 0.13647402, 0.91557693,
       0.37759015, 0.04448156, 0.42337063, 0.01427701, 0.55601035,
       0.32908914, 0.9098057 , 0.19364509, 0.22277103, 0.97742841,
       0.89920785, 0.42133121, 0.55556072, 0.44665896, 0.18892407,
       0.36529222, 0.75596175, 0.44754927, 0.4430441 , 0.87359262,
       0.84757477, 0.10690703, 0.14879538, 0.69485113, 0.44505231,
       0.51097714, 0.70291168, 0.10292151, 0.84202187, 0.10299896,
       0.83276654, 0.85854909, 0.23412702, 0.53360344, 0.12650705,
       0.05381448, 0.81990445, 0.99722377, 0.80044416, 0.22578

In [250]:
target_value = 0.3

In [251]:
np.absolute(X - target_value)

array([0.21679056, 0.01836487, 0.13226985, 0.04361974, 0.60638178,
       0.43941163, 0.4671644 , 0.41096114, 0.06160515, 0.02130682,
       0.11608929, 0.01153932, 0.18904225, 0.10159824, 0.46316895,
       0.29120256, 0.14938085, 0.65288302, 0.39350348, 0.56902249,
       0.46969605, 0.08832045, 0.36846311, 0.27769285, 0.16180493,
       0.07258669, 0.61267169, 0.16483   , 0.09259964, 0.24666096,
       0.01027549, 0.53816603, 0.16387485, 0.16352598, 0.61557693,
       0.07759015, 0.25551844, 0.12337063, 0.28572299, 0.25601035,
       0.02908914, 0.6098057 , 0.10635491, 0.07722897, 0.67742841,
       0.59920785, 0.12133121, 0.25556072, 0.14665896, 0.11107593,
       0.06529222, 0.45596175, 0.14754927, 0.1430441 , 0.57359262,
       0.54757477, 0.19309297, 0.15120462, 0.39485113, 0.14505231,
       0.21097714, 0.40291168, 0.19707849, 0.54202187, 0.19700104,
       0.53276654, 0.55854909, 0.06587298, 0.23360344, 0.17349295,
       0.24618552, 0.51990445, 0.69722377, 0.50044416, 0.07421

In [252]:
X[np.argmin(np.absolute(X-target_value))]

0.31027549026710155

In [253]:
X = np.random.uniform(0, 1, 100)
X

array([0.70031986, 0.47469807, 0.16281925, 0.03111135, 0.26122395,
       0.09288609, 0.31137242, 0.51341433, 0.13082753, 0.50447044,
       0.44553385, 0.58254634, 0.34815742, 0.75154309, 0.58843895,
       0.74270299, 0.86172337, 0.38588875, 0.55850278, 0.80014625,
       0.63615435, 0.87551166, 0.52815866, 0.69594828, 0.24530256,
       0.81881465, 0.11716831, 0.07947148, 0.23291724, 0.97819801,
       0.66896918, 0.67593254, 0.85253906, 0.79746438, 0.61108348,
       0.261602  , 0.42696198, 0.85836431, 0.78706226, 0.73105082,
       0.17698309, 0.72234332, 0.30967725, 0.02606799, 0.50389704,
       0.124032  , 0.58159345, 0.62163028, 0.93558536, 0.03435645,
       0.02828375, 0.12416567, 0.65551255, 0.43287511, 0.04099554,
       0.35152216, 0.92545362, 0.3787232 , 0.83666929, 0.18560618,
       0.39152022, 0.38884631, 0.84867716, 0.67073523, 0.59196361,
       0.72982152, 0.8375834 , 0.74835406, 0.79335752, 0.01317196,
       0.91572349, 0.02772041, 0.13566915, 0.42643526, 0.41488

In [263]:
np.sort(X)

array([0.01317196, 0.01423552, 0.02606799, 0.02772041, 0.02828375,
       0.03111135, 0.03435645, 0.04099554, 0.06670039, 0.07947148,
       0.09288609, 0.11716831, 0.124032  , 0.12416567, 0.13082753,
       0.13566915, 0.15952947, 0.16281925, 0.16427164, 0.17698309,
       0.18560618, 0.23291724, 0.24530256, 0.25472705, 0.26122395,
       0.261602  , 0.30165811, 0.30300676, 0.30967725, 0.31087282,
       0.31137242, 0.33313993, 0.34815742, 0.35152216, 0.3787232 ,
       0.38588875, 0.38884631, 0.38978807, 0.39152022, 0.40103645,
       0.41112638, 0.41488436, 0.42643526, 0.42696198, 0.43287511,
       0.44553385, 0.47469807, 0.49521237, 0.50389704, 0.50447044,
       0.51341433, 0.51804493, 0.52815866, 0.55850278, 0.58159345,
       0.58254634, 0.58843895, 0.58894883, 0.59196361, 0.59273596,
       0.60761908, 0.61108348, 0.62163028, 0.62753248, 0.63017019,
       0.63615435, 0.64270858, 0.65551255, 0.66377093, 0.66896918,
       0.67073523, 0.67566539, 0.67593254, 0.67993535, 0.69594

In [277]:
a = np.sort(X)[::-1]
a

array([0.97819801, 0.93558536, 0.92545362, 0.91572349, 0.87551166,
       0.86172337, 0.85836431, 0.85253906, 0.84867716, 0.8375834 ,
       0.83666929, 0.81881465, 0.80014625, 0.79746438, 0.79728493,
       0.79335752, 0.78706226, 0.75154309, 0.74965507, 0.74835406,
       0.74270299, 0.73105082, 0.72982152, 0.72234332, 0.70031986,
       0.69594828, 0.67993535, 0.67593254, 0.67566539, 0.67073523,
       0.66896918, 0.66377093, 0.65551255, 0.64270858, 0.63615435,
       0.63017019, 0.62753248, 0.62163028, 0.61108348, 0.60761908,
       0.59273596, 0.59196361, 0.58894883, 0.58843895, 0.58254634,
       0.58159345, 0.55850278, 0.52815866, 0.51804493, 0.51341433,
       0.50447044, 0.50389704, 0.49521237, 0.47469807, 0.44553385,
       0.43287511, 0.42696198, 0.42643526, 0.41488436, 0.41112638,
       0.40103645, 0.39152022, 0.38978807, 0.38884631, 0.38588875,
       0.3787232 , 0.35152216, 0.34815742, 0.33313993, 0.31137242,
       0.31087282, 0.30967725, 0.30300676, 0.30165811, 0.26160

In [281]:
b = np.arange(5)
b

array([0, 1, 2, 3, 4])

In [288]:
a[([0,1,2,3,4])]

array([0.97819801, 0.93558536, 0.92545362, 0.91572349, 0.87551166])

In [283]:
def get_n_largest_values(X, n):
    X = np.sort(X)[::-1]
    b = np.arange(n)
    return X[b]

In [284]:
X = np.random.uniform(0, 1, 100)
X

array([0.48793722, 0.59538194, 0.48213127, 0.99763932, 0.51494253,
       0.92002008, 0.37074274, 0.53549277, 0.08602309, 0.67885238,
       0.35117772, 0.47680499, 0.53087316, 0.93442818, 0.55312109,
       0.28827818, 0.62923405, 0.7881211 , 0.91577423, 0.09609928,
       0.48029787, 0.94065118, 0.03291061, 0.58773231, 0.53637772,
       0.87092148, 0.47829422, 0.33121055, 0.01175027, 0.50019787,
       0.50220342, 0.83186571, 0.73104266, 0.42729763, 0.32853755,
       0.92481863, 0.16909951, 0.200229  , 0.71493719, 0.59814934,
       0.33961957, 0.29549286, 0.45311604, 0.68570428, 0.8827198 ,
       0.77131882, 0.03925184, 0.61898293, 0.55894311, 0.49770516,
       0.78820116, 0.72560865, 0.07143542, 0.29983561, 0.49237284,
       0.55102484, 0.13936605, 0.08958715, 0.03710933, 0.54193971,
       0.21564111, 0.8372373 , 0.6856307 , 0.66660678, 0.10449852,
       0.14071245, 0.69379351, 0.78492263, 0.64878357, 0.65347125,
       0.36730095, 0.96582748, 0.45119151, 0.88673019, 0.60548

In [285]:
get_n_largest_values(X, 3)

array([0.99763932, 0.96582748, 0.95949438])