# Missing Values

What to do when we have missing data. You could
1. Drop samples
2. Drop the entire features of a data
3. Replace missing values with either median or mean values of the specific feature

### 1. 1 Dropping Missing Data

In [1]:
import numpy as np
import pandas as pd

# Eaxmple from - https://chrisalbon.com/python/pandas_missing_data.html
raw_data = {'first_name': ['Jason', np.nan, 'Tina', 'Jake', 'Amy'],
        'last_name': ['Miller', np.nan, 'Ali', 'Milner', 'Cooze'],
        'age': [42, np.nan, 36, 24, 73],
        'sex': ['m', np.nan, 'f', 'm', 'f'],
        'preTestScore': [4, np.nan, np.nan, 2, 3],
        'postTestScore': [25, np.nan, np.nan, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['first_name', 'last_name', 'age', 'sex', 'preTestScore', 'postTestScore'])
df

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [2]:
#check how many missing values there are by column
df.isnull().sum()

first_name       1
last_name        1
age              1
sex              1
preTestScore     2
postTestScore    2
dtype: int64

Drop by row

In [3]:
#drop row if all columns of that row are missing
df_cleaned = df.dropna(how='all')
df_cleaned

first_name last_name   age sex  preTestScore  postTestScore
0      Jason    Miller  42.0   m           4.0           25.0
2       Tina       Ali  36.0   f           NaN            NaN
3       Jake    Milner  24.0   m           2.0           62.0
4        Amy     Cooze  73.0   f           3.0           70.0

Drop by column

In [4]:
df['location'] = np.nan
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           NaN            NaN       NaN
2       Tina       Ali  36.0    f           NaN            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [5]:
df.dropna(axis=1, how='all')

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

In [6]:
#set a threshold if there are more than 3 missing in column direction
df.dropna(axis=1, thresh=3)

first_name last_name   age  sex  preTestScore  postTestScore
0      Jason    Miller  42.0    m           4.0           25.0
1        NaN       NaN   NaN  NaN           NaN            NaN
2       Tina       Ali  36.0    f           NaN            NaN
3       Jake    Milner  24.0    m           2.0           62.0
4        Amy     Cooze  73.0    f           3.0           70.0

### 1.2 Filling in Missing Data

Make use of mean, median, and mode. Double check the distribution of values of the column in interest to figure out which methods is most suitable

In [7]:
df['preTestScore'].mean()

3.0

In [8]:
df['postTestScore'].median()

62.0

In [9]:
df['postTestScore'].mode()

0    25.0
1    62.0
2    70.0
dtype: float64

Use .fillna() to fill in missing data

In [10]:
#fill missing values in 'preTestScore' with its mean
df['preTestScore'].fillna(df['preTestScore'].mean(), inplace=True)

In [11]:
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           3.0            NaN       NaN
2       Tina       Ali  36.0    f           3.0            NaN       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [17]:
#groupby sex and fill values with mean
df["postTestScore"].fillna(
    df.groupby("sex")["postTestScore"].transform("mean"), inplace=True)
df

first_name last_name   age  sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0    m           4.0           25.0       NaN
1        NaN       NaN   NaN  NaN           3.0            NaN       NaN
2       Tina       Ali  36.0    f           3.0           70.0       NaN
3       Jake    Milner  24.0    m           2.0           62.0       NaN
4        Amy     Cooze  73.0    f           3.0           70.0       NaN

In [19]:
#select where age and sex are not null
df[df['age'].notnull() & df['sex'].notnull()]

first_name last_name   age sex  preTestScore  postTestScore  location
0      Jason    Miller  42.0   m           4.0           25.0       NaN
2       Tina       Ali  36.0   f           3.0           70.0       NaN
3       Jake    Milner  24.0   m           2.0           62.0       NaN
4        Amy     Cooze  73.0   f           3.0           70.0       NaN

# Categorical Data Handling

Binary data like : {Green, Blue, Yellow}
<br>
<br>
One-hot encoding method:
<br>
{Green}: [1,0,0]<br>
{Green}: [1,0,0]<br>
{Blue}: [0,1,0]<br>
Create binary features corresponding to the number of dataset

In [20]:
edges = pd.DataFrame({'source': [0, 1, 2],
                   'target': [2, 2, 3],
                       'weight': [3, 4, 5],
                       'color': ['red', 'blue', 'blue']})

edges

source  target  weight color
0       0       2       3   red
1       1       2       4  blue
2       2       3       5  blue

In [21]:
edges['source']

0    0
1    1
2    2
Name: source, dtype: int64

In [22]:
edges['color']

0     red
1    blue
2    blue
Name: color, dtype: object

## One-hot Encoding

In [23]:
pd.get_dummies(edges)

source  target  weight  color_blue  color_red
0       0       2       3           0          1
1       1       2       4           1          0
2       2       3       5           1          0

In [24]:
pd.get_dummies(edges[['color']])

color_blue  color_red
0           0          1
1           1          0
2           1          0

In [25]:
weight_dict = {3:"M", 4:"L", 5:"XL"}
edges["weight_sign"] = edges["weight"].map(weight_dict)
edges

source  target  weight color weight_sign
0       0       2       3   red           M
1       1       2       4  blue           L
2       2       3       5  blue          XL

In [27]:
edges = pd.get_dummies(edges)
edges

source  target  weight  color_blue  color_red  weight_sign_L  \
0       0       2       3           0          1              0   
1       1       2       4           1          0              1   
2       2       3       5           1          0              0   

   weight_sign_M  weight_sign_XL  
0              1               0  
1              0               0  
2              0               1

In [28]:
#change to matrix
edges.as_matrix()

/Users/jonghobaeck/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([[0, 2, 3, 0, 1, 0, 1, 0],
       [1, 2, 4, 1, 0, 1, 0, 0],
       [2, 3, 5, 1, 0, 0, 0, 1]])

## Data Binning

When you want to separate values according to a certain interval<br>
1. You need to set the interval [0, 20 , 25, 75, 100]
2. Name the intervals ['Low', 'Okay', 'Good', 'Great']
3. Use pd.cut()
4. The values in a series are transformed to categorical data, which then need to be transformed via get_dummies()

In [29]:
# Example from - https://chrisalbon.com/python/pandas_binning_data.html

raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
        'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
        'name': ['Miller', 'Jacobson', 'Ali', 'Milner', 'Cooze', 'Jacon', 'Ryaner', 'Sone', 'Sloan', 'Piger', 'Riani', 'Ali'],
        'preTestScore': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
        'postTestScore': [25, 94, 57, 62, 70, 25, 94, 57, 62, 70, 62, 70]}
df = pd.DataFrame(raw_data, columns = ['regiment', 'company', 'name', 'preTestScore', 'postTestScore'])
df

regiment company      name  preTestScore  postTestScore
0   Nighthawks     1st    Miller             4             25
1   Nighthawks     1st  Jacobson            24             94
2   Nighthawks     2nd       Ali            31             57
3   Nighthawks     2nd    Milner             2             62
4     Dragoons     1st     Cooze             3             70
5     Dragoons     1st     Jacon             4             25
6     Dragoons     2nd    Ryaner            24             94
7     Dragoons     2nd      Sone            31             57
8       Scouts     1st     Sloan             2             62
9       Scouts     1st     Piger             3             70
10      Scouts     2nd     Riani             2             62
11      Scouts     2nd       Ali             3             70

In [30]:
bins = [0, 25, 50, 75, 100] # Define bins as 0 to 25, 25 to 50, 60 to 75, 75 to 100
group_names = ['Low', 'Okay', 'Good', 'Great']
categories = pd.cut(df['postTestScore'], bins, labels=group_names)
categories

0       Low
1     Great
2      Good
3      Good
4      Good
5       Low
6     Great
7      Good
8      Good
9      Good
10     Good
11     Good
Name: postTestScore, dtype: category
Categories (4, object): [Low < Okay < Good < Great]

In [32]:
#add a new categorical column corresponding th postTestScore
df['categories'] = pd.cut(df['postTestScore'], bins, labels=group_names)
df

regiment company      name  preTestScore  postTestScore categories
0   Nighthawks     1st    Miller             4             25        Low
1   Nighthawks     1st  Jacobson            24             94      Great
2   Nighthawks     2nd       Ali            31             57       Good
3   Nighthawks     2nd    Milner             2             62       Good
4     Dragoons     1st     Cooze             3             70       Good
5     Dragoons     1st     Jacon             4             25        Low
6     Dragoons     2nd    Ryaner            24             94      Great
7     Dragoons     2nd      Sone            31             57       Good
8       Scouts     1st     Sloan             2             62       Good
9       Scouts     1st     Piger             3             70       Good
10      Scouts     2nd     Riani             2             62       Good
11      Scouts     2nd       Ali             3             70       Good

In [33]:
pd.value_counts(df['categories'])

Good     8
Great    2
Low      2
Okay     0
Name: categories, dtype: int64

In [34]:
del df['name']
df

regiment company  preTestScore  postTestScore categories
0   Nighthawks     1st             4             25        Low
1   Nighthawks     1st            24             94      Great
2   Nighthawks     2nd            31             57       Good
3   Nighthawks     2nd             2             62       Good
4     Dragoons     1st             3             70       Good
5     Dragoons     1st             4             25        Low
6     Dragoons     2nd            24             94      Great
7     Dragoons     2nd            31             57       Good
8       Scouts     1st             2             62       Good
9       Scouts     1st             3             70       Good
10      Scouts     2nd             2             62       Good
11      Scouts     2nd             3             70       Good

In [35]:
pd.get_dummies(df)

preTestScore  postTestScore  regiment_Dragoons  regiment_Nighthawks  \
0              4             25                  0                    1   
1             24             94                  0                    1   
2             31             57                  0                    1   
3              2             62                  0                    1   
4              3             70                  1                    0   
5              4             25                  1                    0   
6             24             94                  1                    0   
7             31             57                  1                    0   
8              2             62                  0                    0   
9              3             70                  0                    0   
10             2             62                  0                    0   
11             3             70                  0                    0   

    regiment_Scouts  company_1st  company_2nd  categories_Low  \
0                 0            1            0               1   
1                 0            1            0               0   
2                 0            0            1               0   
3                 0            0            1               0   
4                 0            1            0               0   
5                 0            1            0               1   
6                 0            0            1               0   
7                 0            0            1               0   
8                 1            1            0               0   
9                 1            1            0               0   
10                1            0            1               0   
11                1            0            1               0   

    categories_Okay  categories_Good  categories_Great  
0                 0                0                 0  
1                 0                0                 1  
2                 0                1                 0  
3                 0                1                 0  
4                 0                1                 0  
5                 0                0                 0  
6                 0                0                 1  
7                 0                1                 0  
8                 0                1                 0  
9                 0                1                 0  
10                0                1                 0  
11                0                1                 0

## Using Scikit-learn Preprocessing

In [37]:
raw_example = df.as_matrix()
raw_example[:3]

/Users/jonghobaeck/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([['Nighthawks', '1st', 4, 25, 'Low'],
       ['Nighthawks', '1st', 24, 94, 'Great'],
       ['Nighthawks', '2nd', 31, 57, 'Good']], dtype=object)

In [38]:
data = raw_example.copy()

In [39]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()

In [40]:
raw_example[:, 0]

array(['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons',
       'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts',
       'Scouts'], dtype=object)

In [41]:
le.fit(raw_example[:, 0])

LabelEncoder()

In [42]:
le.classes_

array(['Dragoons', 'Nighthawks', 'Scouts'], dtype=object)

In [43]:
le.transform(raw_example[:, 0])

array([1, 1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 2])

In [44]:
data[:, 0] = le.transform(raw_example[:,0])
data

array([[1, '1st', 4, 25, 'Low'],
       [1, '1st', 24, 94, 'Great'],
       [1, '2nd', 31, 57, 'Good'],
       [1, '2nd', 2, 62, 'Good'],
       [0, '1st', 3, 70, 'Good'],
       [0, '1st', 4, 25, 'Low'],
       [0, '2nd', 24, 94, 'Great'],
       [0, '2nd', 31, 57, 'Good'],
       [2, '1st', 2, 62, 'Good'],
       [2, '1st', 3, 70, 'Good'],
       [2, '2nd', 2, 62, 'Good'],
       [2, '2nd', 3, 70, 'Good']], dtype=object)

## One-hot Encoding Using Sklearn

In [45]:
one_hot_enc = preprocessing.OneHotEncoder()

In [48]:
data[:,0].reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [2],
       [2],
       [2],
       [2]], dtype=object)

In [49]:
one_hot_enc.fit(data[:,0].reshape(-1,1))

/Users/jonghobaeck/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:368: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


OneHotEncoder(categorical_features=None, categories=None,
       dtype=<class 'numpy.float64'>, handle_unknown='error',
       n_values=None, sparse=True)

In [52]:
one_hot_enc.n_values_

/Users/jonghobaeck/anaconda3/lib/python3.7/site-packages/sklearn/utils/deprecation.py:77: DeprecationWarning: Function n_values_ is deprecated; The ``n_values_`` attribute was deprecated in version 0.20 and will be removed 0.22.
  warnings.warn(msg, category=DeprecationWarning)


array([3])

In [53]:
onehotlabels = one_hot_enc.transform(data[:,0].reshape(-1,1)).toarray()
onehotlabels

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])